# Generated by Django 4.0.6 on 2022-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('director', models.TextField(max_length=100)),
                ('actor', models.TextField(max_length=100)),
                ('MusicComposer', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
