# Generated by Django 4.0.6 on 2022-08-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='MusicComposer',
            new_name='music_omposer',
        ),
    ]
